extends TestCase
## Every activity generated by tools/gen_activities.gd (flagged `"validated":
## true` in its JSON) must still pass ActivityValidator against the current
## generated city, and each major district must hold TARGET valid activities
## of every type. Legacy hand-authored activities are validated and reported
## but only counted if they pass.

const TARGET := 3
const DISTRICTS: Array[StringName] = [&"skaa_slums", &"merchant", &"noble", &"docks", &"market"]
const TYPES: Array[StringName] = [&"coin_race", &"rooftop_pursuit", &"obligator_ambush", &"crowd_riot"]

static var _plan: CityPlan
static var _report: Dictionary = {}   # id -> {district, type, errors, validated}


func _run_all() -> void:
	if not _report.is_empty():
		return
	_plan = CityPlan.load_from_file()
	var v := ActivityValidator.new(_plan, 1337)
	var flagged := {}
	var dir := DirAccess.open("res://src/mission/activities/data")
	for f in dir.get_files():
		if f.ends_with(".json") and f != "collectibles.json":
			var parsed = JSON.parse_string(FileAccess.get_file_as_string("res://src/mission/activities/data/" + f))
			if typeof(parsed) == TYPE_DICTIONARY and bool(parsed.get("validated", false)):
				flagged[StringName(parsed["id"])] = true
	for a in ActivityData.load_all():
		var start := v.resolve_start(a.id)
		var errs := v.validate(a, start)
		var district: StringName = &""
		if start != Vector3.INF:
			district = _plan.district_at(Vector2(start.x, start.z))
		_report[a.id] = {"district": district, "type": a.type, "errors": errs, "validated": flagged.has(a.id)}


func test_generated_activities_are_clear_of_geometry() -> void:
	_run_all()
	var n := 0
	for id: StringName in _report:
		var r: Dictionary = _report[id]
		if r["validated"]:
			n += 1
			assert_true((r["errors"] as Array).is_empty(), "%s: %s" % [id, ", ".join(r["errors"])])
	assert_gt(n, 20, "generated activities present (%d)" % n)


func test_each_major_district_has_three_valid_activities_per_type() -> void:
	_run_all()
	var counts := {}
	for id: StringName in _report:
		var r: Dictionary = _report[id]
		if (r["errors"] as Array).is_empty():
			var key := [r["district"], r["type"]]
			counts[key] = int(counts.get(key, 0)) + 1
	for d in DISTRICTS:
		for t in TYPES:
			var c := int(counts.get([d, t], 0))
			assert_true(c >= TARGET, "%s / %s has %d valid activities" % [d, t, c])


func test_report_legacy_activity_problems() -> void:
	_run_all()
	for id: StringName in _report:
		var r: Dictionary = _report[id]
		if not r["validated"] and not (r["errors"] as Array).is_empty():
			print("    legacy %s (%s): %s" % [id, r["district"], ", ".join(r["errors"])])
	assert_true(true)


func test_every_activity_has_exactly_one_start_marker() -> void:
	var plan := CityPlan.load_from_file()
	var counts := {}
	for m: Dictionary in plan.markers:
		var id := str(m.get("activity_id", ""))
		if id != "":
			counts[id] = int(counts.get(id, 0)) + 1
	for a in ActivityData.load_all():
		assert_eq(int(counts.get(String(a.id), 0)), 1, "%s has one start marker" % a.id)


func test_pursuit_gap_needs_an_anchor() -> void:
	# Two 10 m roofs with a 9 m street between them.
	var boxes: Array[AABB] = [AABB(Vector3(0, 0, -5), Vector3(10, 10, 10)), AABB(Vector3(19, 0, -5), Vector3(10, 10, 10))]
	var a := Vector3(5, 10.25, 0)
	var b := Vector3(24, 10.25, 0)
	var gaps := ActivityValidator.air_gaps(a, b, boxes)
	assert_eq(gaps.size(), 1)
	var v := ActivityValidator.new(CityPlan.load_from_file(), 1337)
	assert_false(v.pursuit_leg_errors(1, a, b, boxes, PackedVector3Array()).is_empty(), "no anchor: can't jump the street")
	var lamp := PackedVector3Array([Vector3(14.5, 3.0, 4.0)])
	assert_true(v.pursuit_leg_errors(1, a, b, boxes, lamp).is_empty(), "a street lamp makes it a steel jump")
	# A narrow alley is a running leap, no anchor needed.
	var alley: Array[AABB] = [AABB(Vector3(0, 0, -5), Vector3(10, 10, 10)), AABB(Vector3(13, 0, -5), Vector3(10, 10, 10))]
	assert_true(v.pursuit_leg_errors(1, a, Vector3(18, 10.25, 0), alley, PackedVector3Array()).is_empty())
